services:

  mongo:
    image: mongo:8
    container_name: comfacauca-mongo

    volumes:
      - mongo_data:/data/db


  backend:
    build: ./backend
    container_name: comfacauca-backend

    ports:
      - "3000:3000"

    volumes:
      - ./backend/uploads:/app/uploads

    depends_on:
      - mongo


  frontend:
    build: ./frontend
    container_name: comfacauca-frontend

    ports:
      - "5173:5173"

    depends_on:
      - backend


volumes:
  mongo_data: